import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'

import { Form, Button, Container } from 'react-bootstrap'

export default function Home() {
  const router = useRouter();
  const [walletAddress, setWalletAddress] = useState("");

  const GoToliftPage = (e) => {
    e.preventDefault();
    if(walletAddress !== "") {
      router.push(`/nfts/${walletAdderess}`)
    }

  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
          <Container>
            <Form onSubmit={GoToliftPage}>
              <Form.Group className="mb-3" controlId="formBasicEmail">
                <Form.Label>Wallet address</Form.Label>
                <Form.Control value={walletAddress} onChange={(e) => setWalletAddress(e.target.value)} type="text" placeholder="Enter wallet address" />
              </Form.Group>
              <Button variant="primary" type="submit">
                Search Nfts
              </Button>
            </Form>
          </Container>
          </div>
          );
        }
